name: AnchorEngineSpigot
version: '${version}'
main: top.alwaysready.anchorengine.spigot.AnchorEngineSpigot
api-version: '1.18'
authors: [ AlwaysReadyWby ]
description: A plugin that works to send custom UI to clients installed with its mod counterpart
depend:
  - PlaceholderAPI
softdepend:
  - BetonQuest

commands:
  anchor_engine:
    aliases:
      - anchor
      - anch
      - ane
permissions:
  anchor:
    children:
      anchor.admin:
        default: op
      anchor.push:
        default: op
      anchor.show:
        children:
          anchor.show.base:
            default: op
          anchor.show.others:
            default: op
      anchor.close:
        children:
          anchor.close.base:
            default: op
          anchor.close.others:
            default: op
      anchor.menu:
        children:
          anchor.menu.base:
            default: true
          anchor.menu.others:
            default: op
      anchor.overlay:
        children:
          anchor.overlay.base:
            default: op
          anchor.overlay.others:
            default: op
      anchor.danmaku:
        default: op
      anchor.version:
        default: true